sdk: "/tmp/sdks/rhodes-2.1.0"
sdkversion: 2.1.0
name: jdcwest2011-rhodes
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.0
  emulator: 4.0.1
  provisionprofile:
  codesignidentity:
  entitlements:
extensions: ["json", "another-extension"]
