--- 
name: JDC West
extensions: 
- json
bbver: 6.0
android: 
  version: 2.1
sdk: C:/InstantRhodes/ruby/lib/ruby/gems/1.8/gems/rhodes-2.2.6
build: debug
applog: rholog.txt
version: 1.0
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
sdkversion: 2.1.0
vendor: rhomobile
iphone: 
  provisionprofile: 
  sdk: iphonesimulator4.0
  codesignidentity: 
  entitlements: 
  configuration: Debug
  emulator: 4.0.1
