--- 
extensions: 
- json
name: JDC West
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-2.2.0
android: 
  version: 2.1
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.1.0
iphone: 
  provisionprofile: 
  sdk: iphonesimulator4.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
  emulator: 4.0.1
