--- 
name: JDC West
extensions: 
- json
bbver: 4.6
android: 
  version: 2.1
sdk: /home/steven/.rvm/gems/ruby-1.9.2-p136/gems/rhodes-2.2.6
build: debug
applog: rholog.txt
version: 1.0
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
sdkversion: 2.1.0
vendor: rhomobile
iphone: 
  provisionprofile: 
  sdk: iphonesimulator4.0
  codesignidentity: 
  entitlements: 
  configuration: Debug
  emulator: 4.0.1
